### ISSUE TITLE
Pods don't stay up

### ISSUE THREAD

**Issue by jimcurtis** [6fusion/couch-kubernetes#1]
I tried this on a 1.7.3 k8s cluster.  The pods keep crashing.  kubectl logs couchdb-0 -c couchdb shows:

[info] 2017-08-31T22:10:46.389146Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.7.0> -------- Application couch_log started on node 'couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local'
[info] 2017-08-31T22:10:46.395723Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.7.0> -------- Application folsom started on node 'couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local'
[info] 2017-08-31T22:10:46.440905Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.7.0> -------- Application couch_stats started on node 'couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local'
[info] 2017-08-31T22:10:46.441177Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.7.0> -------- Application khash started on node 'couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local'
[info] 2017-08-31T22:10:46.451174Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.7.0> -------- Application couch_event started on node 'couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local'
[info] 2017-08-31T22:10:46.457016Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.7.0> -------- Application ibrowse started on node 'couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local'
[info] 2017-08-31T22:10:46.462974Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.7.0> -------- Application ioq started on node 'couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local'
[info] 2017-08-31T22:10:46.463237Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.7.0> -------- Application mochiweb started on node 'couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local'
[info] 2017-08-31T22:10:46.476409Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.202.0> -------- Apache CouchDB 2.1.0 is starting.

[info] 2017-08-31T22:10:46.476552Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.203.0> -------- Starting couch_sup
[notice] 2017-08-31T22:10:46.499820Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.89.0> -------- config: [admins] admin set to -pbkdf2-ef2cfbc89876fe08330bc52958100f700e24cbae,bab7ec81f40ccf85e660647093a2e289,10 for reason nil
[notice] 2017-08-31T22:10:46.532324Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.89.0> -------- config: [couchdb] uuid set to e147a3dcbb87c51b6d6209a8f7356306 for reason nil
[info] 2017-08-31T22:10:46.586140Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.208.0> -------- open_result error {not_found,no_db_file} for _users
[error] 2017-08-31T22:10:46.588235Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.251.0> -------- Could not open file ./data/_users.couch: permission denied
[info] 2017-08-31T22:10:46.588343Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.208.0> -------- open_result error {error,eacces} for _users
[error] 2017-08-31T22:10:46.589256Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.245.0> -------- CRASH REPORT Process  (<0.245.0>) with 1 neighbors exited with reason: no match of right hand value {error,eacces} at couch_auth_cache:ensure_users_db_exists/2(line:447) <= couch_auth_cache:open_auth_db/0(line:419) <= couch_auth_cache:reinit_cache/1(line:281) <= couch_auth_cache:init/1(line:164) <= gen_server:init_it/6(line:328) <= proc_lib:init_p_do_apply/3(line:240) at gen_server:init_it/6(line:352) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {couch_auth_cache,init,['Argument__1']}, ancestors: [couch_secondary_services,couch_sup,<0.202.0>], messages: [], links: [<0.212.0>,<0.247.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 27, reductions: 366
[error] 2017-08-31T22:10:46.590568Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.202.0> -------- Error starting Apache CouchDB:

    {error,{shutdown,{failed_to_start_child,couch_secondary_services,{shutdown,{failed_to_start_child,auth_cache,{{badmatch,{error,eacces}},[{couch_auth_cache,ensure_users_db_exists,2,[{file,"src/couch_auth_cache.erl"},{line,447}]},{couch_auth_cache,open_auth_db,0,[{file,"src/couch_auth_cache.erl"},{line,419}]},{couch_auth_cache,reinit_cache,1,[{file,"src/couch_auth_cache.erl"},{line,281}]},{couch_auth_cache,init,1,[{file,"src/couch_auth_cache.erl"},{line,164}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,240}]}]}}}}}}

[error] 2017-08-31T22:10:46.593113Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.212.0> -------- Supervisor couch_secondary_services had child auth_cache started with couch_auth_cache:start_link() at undefined exit with reason no match of right hand value {error,eacces} at couch_auth_cache:ensure_users_db_exists/2(line:447) <= couch_auth_cache:open_auth_db/0(line:419) <= couch_auth_cache:reinit_cache/1(line:281) <= couch_auth_cache:init/1(line:164) <= gen_server:init_it/6(line:328) <= proc_lib:init_p_do_apply/3(line:240) in context start_error
[error] 2017-08-31T22:10:46.593472Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.203.0> -------- Supervisor couch_sup had child couch_secondary_services started with couch_secondary_sup:start_link() at undefined exit with reason {shutdown,{failed_to_start_child,auth_cache,{{badmatch,{error,eacces}},[{couch_auth_cache,ensure_users_db_exists,2,[{file,"src/couch_auth_cache.erl"},{line,447}]},{couch_auth_cache,open_auth_db,0,[{file,"src/couch_auth_cache.erl"},{line,419}]},{couch_auth_cache,reinit_cache,1,[{file,"src/couch_auth_cache.erl"},{line,281}]},{couch_auth_cache,init,1,[{file,"src/couch_auth_cache.erl"},{line,164}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"p..."},...]}]}}} in context start_error
[error] 2017-08-31T22:10:46.593825Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.201.0> -------- CRASH REPORT Process  (<0.201.0>) with 0 neighbors exited with reason: {{shutdown,{failed_to_start_child,couch_secondary_services,{shutdown,{failed_to_start_child,auth_cache,{{badmatch,{error,eacces}},[{couch_auth_cache,ensure_users_db_exists,2,[{file,"src/couch_auth_cache.erl"},{line,447}]},{couch_auth_cache,open_auth_db,0,[{file,"src/couch_auth_cache.erl"},{line,419}]},{couch_auth_cache,reinit_cache,1,[{file,"src/couch_auth_cache.erl"},{line,281}]},{couch_auth_cache,init,1,[{file,"src/couch_auth_cache.erl"},{line,164}]},{gen_server,init_it,6,[{file,"gen_ser..."},...]},...]}}}}},...} at application_master:init/4(line:134) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {application_master,init,['Argument__1','Argument__2',...]}, ancestors: [<0.200.0>], messages: [{'EXIT',<0.202.0>,normal}], links: [<0.200.0>,<0.7.0>], dictionary: [], trap_exit: true, status: running, heap_size: 987, stack_size: 27, reductions: 152
[info] 2017-08-31T22:10:46.594229Z couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local <0.7.0> -------- Application couch exited with reason: {{shutdown,{failed_to_start_child,couch_secondary_services,{shutdown,{failed_to_start_child,auth_cache,{{badmatch,{error,eacces}},[{couch_auth_cache,ensure_users_db_exists,2,[{file,"src/couch_auth_cache.erl"},{line,447}]},{couch_auth_cache,open_auth_db,0,[{file,"src/couch_auth_cache.erl"},{line,419}]},{couch_auth_cache,reinit_cache,1,[{file,"src/couch_auth_cache.erl"},{line,281}]},{couch_auth_cache,init,1,[{file,"src/couch_auth_cache.erl"},{line,164}]},{gen_server,init_it,6,[{file,"gen_ser..."},...]},...]}}}}},...}
[os_mon] memory supervisor port (memsup): Erlang has closed
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
{"Kernel pid terminated",application_controller,"{application_start_failure,couch,{{shutdown,{failed_to_start_child,couch_secondary_services,{shutdown,{failed_to_start_child,auth_cache,{{badmatch,{error,eacces}},[{couch_auth_cache,ensure_users_db_exists,2,[{file,\"src/couch_auth_cache.erl\"},{line,447}]},{couch_auth_cache,open_auth_db,0,[{file,\"src/couch_auth_cache.erl\"},{line,419}]},{couch_auth_cache,reinit_cache,1,[{file,\"src/couch_auth_cache.erl\"},{line,281}]},{couch_auth_cache,init,1,[{file,\"src/couch_auth_cache.erl\"},{line,164}]},{gen_server,init_it,6,[{file,\"gen_server.erl\"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,\"proc_lib.erl\"},{line,240}]}]}}}}},{couch_app,start,[normal,[]]}}}"}
/opt/bin/couch-wrapper: line 20:    11 User defined signal 2   /opt/couchdb/bin/

**Comment by p80n** [comment]
I think this was due to lack of permission to write to the volume mount. I've updated the launcher script to ensure correct ownership on the couch directories.
I've pushed up a rebuilt docker image, so you should be able to just redeploy the StatefulSet and let it pull down the latest 6fusion/couchdb:alpha image to see if this fixes your issue.

**Comment by jimcurtis** [comment]
Ok, that  seemed to fix the issue.  The Pods stay up now.

**Comment by p80n** [comment]
Awesome - thanks for the update!
