### ISSUE TITLE
Could not get it to work

### ISSUE THREAD

**Issue by huineng** [6fusion/couch-kubernetes#3]
It's a pity i could not get it to work.

I followed the instructions , installation want ok , pods, services , pvc and stateful sets created
i could port forward and open fauxton, create a database

but the 3 default db's _users _replicator _global_changes where not there and displayed the message "This database failed to load"

the curl to _membership did not return what i think you would expect

```
{
  "all_nodes": [
    "couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local"
  ],
  "cluster_nodes": [
    "couchdb@couchdb-0.couchdb-internal.default.svc.cluster.local",
    "couchdb@couchdb-1.couchdb-internal.default.svc.cluster.local",
    "nonode@nohost"
  ]
}
```

What could be the reason for this as i could not really discover any log that could tell me this 

thansk

**Comment by p80n** [comment]
A couple questions: 
- What version of kubernetes are you using?
- Are you deploying into a cloud provider? If so, which one (AWS, GKE, ...)?

Probably the logs from the sidecar container would be most helpful in figuring out what is going on.
If you want to paste those back here, I'll take a look and see if we can figure out what is breaking.

**Comment by huineng** [comment]
i'm deploying on bluemix , v 1.7
I got it now to work deleting all and starting from scratch again .

I really like the implementation , but it's not really clear to me, how if finally got it to work
I removed the passwords in the cluster-sidecar (as like in your developer branch ) and did not change any other password 

Also scaling is not working in my opinion 

when i got 2 pods running ( curl them and see 0 and 1 like expected)
then i scale to 3 replicas (created a pvc beforehand ) 
then
(curl again but now only see pod 2 )
looking into pod 2 fauxton , nothing has been initialized (no db's created)
then when i scale down to 2 the curl shows again what to expect (0 and 1)

So i think i has something to do with the cluster-sidecar that is not doing what it is supposed to do when scaling up (adding a node to the cluster)
But on the other side, your documentation didn't mention anything on scaling capabilities so this might not have been build in ..

also what is the purpose of the 2 containers tagged latest ? are they to replace alpha ?
thanks

**Comment by p80n** [comment]
My understanding of scaling Couch DB (and I'm not an expert - so please correct me if I'm wrong) - is that once you've created a cluster, you cannot simply add more nodes to it.
I'm going by the docs here: http://docs.couchdb.org/en/2.1.1/cluster/sharding.html#scaling-out, specifically, section 11.5.4.

I can certainly update the documentation to include this limitation - and possibly also update the sidecar to detect when an attempt is made to change the cluster size.

> also what is the purpose of the 2 containers tagged latest ?

If you are referring to the other images hosted on Docker Hub, they're basically the same at this point. I'll try to update the documentation on the Docker Hub page to include release notes between versions, and update this repo accordingly (once I have a chance).

Let me know if I haven't fully addressed any of your concerns.
Thanks for the feedback!

**Comment by huineng** [comment]
Peyton, you've done a great job ..
I got it all working now , just a summary of how i prefer to do it. 

```
1.create 2 pvc upfront based on pvc.yaml (name would be volumeClaimTemplates.metadata.name +"-" + StatefulSet.metadata.name + "-" + 0 to number of cluster nodes)
2.wait till available
3.apply couchdb-statefulset.yml
4.check if all works curl -s -u username:password (clusterip of couchdb service):5984/_membership
```

how to scale your cluster afterwards
```
1. add a pvc (like point 1 above ending with new cluster seq)
2. scale your stateful set 
3. this database will be completely empty and not initialized (not sure why)
3. add _users _replicator _global_changes
4. update your first cluster node by adding the new node
   curl -u username:password -X PUT "http://{{pod cluster ip}}:5986/_nodes/couchdb@{{new node}}" -d {}   you can get the new node by doing a standard curl _membership and then just changing the sequence number
```

maybe whenever you might consider it worth having a look ..

1. why is the new instance not initialized after doing a scale ?
2. the adding the new node could be a routine in your go where you would check if the new created instance is part of the _membership of the first instance , if not then add the new instance to the the first instance _nodes

thanks anyway for your help

**Comment by huineng** [comment]
finally, i would not invest in this , if one wants to scale afterwards, the procedure above can help, but scaling up is one thing, it can be completely messy scaling down (shards need to be moved etc.. ) so leave that up to the user themselves.

I think you can close this ticket and thanks again

**Comment by p80n** [comment]
Forgot to close this out.
Thanks again for taking the time to provide feedback!
